version: 0.2
phases:
  install:
    commands:
      - cd ./index-photos
      - ls
      - pip install -r requirements.txt 
      - cd ../  
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket photo-album-lambdas-hw2 --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputsamtemplate.yml
