AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD For HW2 Lambdas
Resources:
  CDIndexPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos 
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./index-photos
      Description: 'Lambda function for indexing incoming photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::215814922646:role/service-role/index-photos-role-3ggizpuo'
      Environment:
        Variables:
          REGION: us-east-1
  CDSearchPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos 
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos
      Description: 'Lambda function for searching for photos with labels that match a query'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::215814922646:role/service-role/search-photos-role-583fm9jv'
      Environment:
        Variables:
          REGION: us-east-1
